_usage()
{
cat <<EOF
jsh {module} {args}...

where {module} {args}.. is one of:
      die {message-args}...
      invoke {module}... {args}...
      installation {cmd} {args}...
      module {cmd} {args}...
      with {context-cmd} {context-args}... -- {encapsulated-cmd} {encapsulated-args}...

type 'jsh help' for more details.
EOF
}

